### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by zablon-oigo** [CrypticNothings/fight4privacy#19]
**Describe the solution you'd like**
I would like to redesign the hero section to be more appealing if that okay with you

![Screenshot 2023-11-06 at 20-38-29 Fight for Online Privacy](https://github.com/CrypticNothings/fight4privacy/assets/143833326/ce3ffc36-c0f4-4fbd-855c-336a6b8cd557)

**Comment by CrypticNothings** [comment]
Go for it! I don't want to use that picture anyways and my attention is focused somewhere else on this project right now. So if you have a vision I'd like to see it.

**Comment by zablon-oigo** [comment]
Great, will share some designs  for you to choose

**Comment by zablon-oigo** [comment]
Hello, Checkout this design tell me which one you prefer
![Screenshot 2023-11-07 at 14-29-06 Fight for Online Privacy](https://github.com/CrypticNothings/fight4privacy/assets/143833326/edcf815a-a9bc-4892-a14c-6c2b77a6e464)
![Screenshot 2023-11-07 at 14-29-34 Fight for Online Privacy](https://github.com/CrypticNothings/fight4privacy/assets/143833326/8bc991d7-b5cc-4130-b38f-683943fde1e9)

**Comment by zablon-oigo** [comment]
Few Update checkout this design, I would love to here your review
1. Added animation effect for hamburgermenu for smooth transition
2. decided to change the main part of the web to be more appealing to the end user for them to be curious and  click  the link and read 
3. made a footer to suit the site appearnce
4. some of the design are how the site would appear if someone is on a smaller screen
5. There is still more effects to be added working on it
![Screenshot 2023-11-07 at 16-15-16 Fight for Online Privacy](https://github.com/CrypticNothings/fight4privacy/assets/143833326/c20d62f0-559f-4d52-87a8-4532f5528d4a)

![Screen Shot 2023-11-07 at 16 17 31](https://github.com/CrypticNothings/fight4privacy/assets/143833326/a7ac7f75-89d1-4e5a-8d81-e2d1a13b278d)
![Screen Shot 2023-11-07 at 16 17 31](https://github.com/CrypticNothings/fight4privacy/assets/143833326/7c22c039-0474-4e5e-a2a7-6579f53dde19)

**Comment by CrypticNothings** [comment]
Beautiful. On the first 2 examples you have I like the bottom one better which it looks like you chose that one to use for the rest of the examples anyways. Which looks really good. Thank you for doing the Scam with picture layout. That's pretty much what I had in mind and you knocked it out. Great work. Where did you source all the pictures you used?

**Comment by CrypticNothings** [comment]
The one scam left on its own at the bottom makes me what to add more there to even it up.

**Comment by zablon-oigo** [comment]
I sourced the images from a site called **Istock**, my concern is what if you have multiple writers who want to write articles on your site, what will happen, have you thought about scaling your site as you progress in the future

**Comment by zablon-oigo** [comment]
I'm glad to hear that you're excited about your project and the response you've received so far. It's important to pace yourself and avoid rushing things, especially when you're managing a project or initiative. Taking your time to plan and execute your ideas can lead to better outcomes in the long run. Working on your project during your favorite time, late at night, when you can focus and avoid distractions, is a good strategy.

If you have any questions or need advice as you continue to develop your project, feel free to ask. I'm here to help, and I'm always available to assist you with any information or guidance you may need. Good luck with your project, and I hope it turns out to be a great success!

**Comment by CrypticNothings** [comment]
Alright well I'm gonna need your help tonight. This is the first time actually getting help and I'm used to having all just files for everything and not grouping in folders. I know that's very messy. But now the folders are throwing me off because I don't see yours listed under pages.

**Comment by zablon-oigo** [comment]
Hello, I used a different stack to design the navigation menu :
navigate to the command line

> cd navigation-menu

### to view the project locally 
in your command line run the command 

>  **npm run dev** 

navigate to your browser type:           

> **localhost:5173**

**Comment by zablon-oigo** [comment]
> Alright well I'm gonna need your help tonight. This is the first time actually getting help and I'm used to having all just files for everything and not grouping in folders. I know that's very messy. But now the folders are throwing me off because I don't see yours listed under pages.

**Let me know if you are able to run the project locally**

**Comment by CrypticNothings** [comment]
Oh ok...it'll be tonight. Sorry...wasn't expecting a response so quick. Things at work have been....peaking....lately for me and it's taken a toll on me. But I need this distraction so I want to get back in it and this was one of my concerns right besides other stuff I'm doing.

**Comment by zablon-oigo** [comment]
Alright keep me in the loop

**Comment by CrypticNothings** [comment]
No, I guess not. I don't have CLI. I really have only used "Visual Studio-to-Github Desktop-to-Github". I opened this using Git-Bash but I'm not really familiar with that yet or know it well. The trio method I mentioned before has always been my go to. Are you sure you still want in on this with me? lol

**Comment by CrypticNothings** [comment]
It just seems weird that I cannot select whatever folder I want to deploy from. Only /root and /docs. So I feel like simply renaming your navigation-menu folder to /docs would get me where I want. There must be something I'm missing and/or not understanding because that just seems silly to me.

**Comment by zablon-oigo** [comment]
Hello, Here is a pictorial description, check it out
![Screenshot (536)](https://github.com/CrypticNothings/fight4privacy/assets/143833326/22e005a1-1d52-4180-9621-b2ada3a82fed)

**Comment by CrypticNothings** [comment]
Ah, alright. I'll try that after work. Wish we weren't on complete opposite schedules. Thank you though.

**Comment by CrypticNothings** [comment]
Ok, so I had to reinstall Git Bash because mine was not installed with the correct things to set up with this site. Now I can and can CD into fight4privacy. But when I do what you said I get this: 
$ npm run dev

> navigation-menu@0.0.0 dev
> vite

'vite' is not recognized as an internal or external command,
operable program or batch file.

I'll check with ChatGPT see if I can find out where to go from there.

**Comment by CrypticNothings** [comment]
Ok, I believe I got what I needed and am up to speed where you wanted me. 

  VITE v4.5.0  ready in 363 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

**Comment by zablon-oigo** [comment]
Great, now head to your browser and type :

**localhost:5173**

**Comment by CrypticNothings** [comment]
Oh I see. Ok...so my problem with that is probably because I work from at least 3 different computers. Mainly one. But I jump around between alot. I only have git Bash on one. Maybe 2.

**Comment by CrypticNothings** [comment]
I guess this is throwing me off. I'm used to constantly previewing the site in visual studio to see how it looks. Then after I merge I'm constantly deploying the page to see where that's at compared to my visual studio progress. Should I clean up some of the other files now that aren't getting used if any? I'm just trying to see the full picture of this process as it helps me understand better.

**Comment by zablon-oigo** [comment]
I have a suggestion , Remove all the extra project files and save them  in  another separate folder on your computer ,
you project should remain with only navigation-menu folder try deploying again  , 
if the issue persist , I think it will be better if we can have a virtual meeting if that's okay with you

**Comment by zablon-oigo** [comment]
> I guess this is throwing me off. I'm used to constantly previewing the site in visual studio to see how it looks. Then after I merge I'm constantly deploying the page to see where that's at compared to my visual studio progress. Should I clean up some of the other files now that aren't getting used if any? I'm just trying to see the full picture of this process as it helps me understand better. Also, I'm used to checking from my phone and as I mentioned other computers.

Hey were you able to manage ?

**Comment by CrypticNothings** [comment]
Sorry I'm on a vacation thing right now. I'm not ignoring you. Just gonna be real slow on responding for the week. Deleting everything didn't seem to work though. Think maybe I just need to learn your way and dedicate a computer for this project maybe.

**Comment by zablon-oigo** [comment]
Hello,
Thank you for reaching out, and I appreciate your honesty about where you stand with the project. No need to worry at all – we're here to work together and support each other's growth. I understand that transitioning into a new field can be challenging, and I'm more than happy to assist you every step of the way.
Firstly, I want to assure you that  It's completely normal to feel a bit overwhelmed when dealing with new tools and files, but we're in this together.
If you're unsure about where to go from here, please don't hesitate to ask me any questions. I'm here to help guide you through the project and address any concerns you may have. Feel free to point out specific areas that are confusing or ask for clarification on certain aspects of the project structure. Learning is a gradual process, and we have plenty of time to work through it.
I'm genuinely excited to continue collaborating with you until we complete the project. Your dedication to transitioning into this field is commendable, and I'm here to provide the support you need. Remember, there's no need to feel bad for not knowing everything – we're all constantly learning and growing in this dynamic field.
Let's keep the lines of communication open, and feel free to reach out whenever you need assistance or clarification—looking forward to progressing together on this project!

**Comment by CrypticNothings** [comment]
Thank you so much for that reassuring reply. Could you possibly point me towards some good reading material, sites, classes that go into more of what you added? I've only barely scratched the surface when it comes to .json. anything outside of say....Codepen style building is out of my comfort zone. I'm used to the 3 languages and getting them to work together and view. I'm trying to understand all the folders you added and different file types and why.

**Comment by zablon-oigo** [comment]
Here are some resources to help you deepen your understanding of web development, including React, and more advanced concepts:

1. **React.js:**
   - [Scrimba](https://www.scrimba.com/): Offers interactive coding screencasts on React.js. It's a great platform to learn by doing.
   - [FreeCodeCamp](https://www.freecodecamp.org/): Provides a comprehensive curriculum on web development, including React, along with hands-on projects.

3. **Web Development Fundamentals:**
   - [W3Schools](https://www.w3schools.com/): A great resource for beginners and beyond, offering tutorials on HTML, CSS, JavaScript, and more.
   - [Mozilla Developer Network (MDN) Web Docs](https://developer.mozilla.org/en-US/): In-depth documentation and tutorials on web technologies.

4. **Advanced Web Development:**
   - [Udacity](https://www.udacity.com/): Offers nanodegree programs on various topics, including full-stack web development and React.
Remember to practice as much as possible by working on real projects. This hands-on experience is invaluable in solidifying your understanding and building confidence in more complex coding scenarios.

**Comment by zablon-oigo** [comment]
About the file structure I need to reorganize the structure then, I will explain what I have done, Is that okay?
